import { ArrowDown, ArrowRight, Check, Command, MousePointer2, Palette, Sparkles, Wand2 } from "lucide-react";
import { Link } from "wouter";
import { MiniCTA, PrimaryButton, QuietButton, SectionHeader } from "@/components/luma/SiteShell";
import StudioPreview from "@/components/luma/StudioPreview";

const steps = [
  { n: "01", title: "Discover", body: "Find a direction.", icon: Sparkles },
  { n: "02", title: "Download", body: "Bring Studio to your desktop.", icon: ArrowDown },
  { n: "03", title: "Design", body: "Shape the idea on canvas.", icon: Palette },
  { n: "04", title: "Publish", body: "Refine it until it feels yours.", icon: Wand2 },
];

export default function Home() {
  return <div>
    <section className="grain relative overflow-hidden border-b border-black/[.06] bg-[#fbfaf8] pt-16 sm:pt-24"><div className="absolute inset-0 -z-10 bg-[radial-gradient(circle_at_75%_18%,rgba(255,203,216,.42),transparent_32%),radial-gradient(circle_at_18%_72%,rgba(247,225,213,.32),transparent_27%)]" /><div className="container"><div className="grid items-center gap-12 lg:grid-cols-[.88fr_1.12fr] lg:gap-8"><div className="pb-6 lg:pb-14"><div className="reveal eyebrow text-primary">Luma / the intelligent web design studio</div><h1 className="display reveal mt-6 max-w-[630px] text-[clamp(56px,8vw,110px)] font-semibold leading-[.86] [animation-delay:80ms]">Design the web <span className="text-primary">with intelligence.</span></h1><p className="reveal mt-8 max-w-[510px] text-lg leading-8 text-muted-foreground [animation-delay:160ms]">Luma helps creators generate, design, remix, and refine websites with more room for the good ideas.</p><div className="reveal mt-9 flex flex-wrap gap-3 [animation-delay:240ms]"><PrimaryButton href="/download">Download Luma Studio</PrimaryButton><QuietButton href="/inspiration">Explore Inspiration <ArrowRight size={15} /></QuietButton></div></div><div className="relative min-h-[360px] overflow-visible sm:min-h-[500px]"><div className="absolute -right-[13%] top-[2%] h-[95%] w-[120%] overflow-hidden rounded-[2rem] border border-black/10 bg-[#ead6d0] shadow-[0_40px_100px_rgba(83,40,47,.17)] sm:-right-[8%]"><img src="/manus-storage/luma-hero-orb_56dc3994.png" alt="Abstract pink ribbon and glass orb" className="hero-orb h-full w-full object-cover" /><div className="absolute left-5 top-5 rounded-full bg-white/75 px-3 py-2 font-mono text-[10px] text-black/60 backdrop-blur">LUMA / 01</div><div className="absolute bottom-5 left-5 flex items-center gap-2 rounded-full bg-[#21191a] px-3 py-2 font-mono text-[10px] text-white/75"><span className="h-1.5 w-1.5 rounded-full bg-[#ffb6ca]" /> Studio preview</div></div></div></div><div className="border-t border-black/[.08] py-4 text-xs text-muted-foreground"><span className="eyebrow">The public website explains. Luma Studio is where the design happens.</span></div></div></section>

    <section className="container py-16 sm:py-20"><div className="grid items-center gap-10 lg:grid-cols-[.72fr_1.28fr] lg:gap-16"><div><div className="eyebrow text-primary">The actual work starts here</div><h2 className="display mt-4 text-4xl font-semibold leading-[.98] sm:text-5xl">Your ideas become websites inside Luma Studio.</h2><p className="mt-5 max-w-[410px] leading-7 text-muted-foreground">A desktop application built for the messy middle: the part where a rough direction becomes a point of view.</p><div className="mt-7 flex flex-wrap gap-3"><PrimaryButton href="/download">Download Studio</PrimaryButton><QuietButton href="/features">Explore features</QuietButton></div></div><StudioPreview compact /></div></section>

    <section className="border-y border-black/[.07] bg-[#f4efeb] py-16 sm:py-20"><div className="container"><SectionHeader eyebrow="How it works" title="A simple path from idea to website." body="The website is the front door. Studio is the room where you make the thing." /><div className="mt-10 grid gap-px overflow-hidden rounded-[1.5rem] border border-black/10 bg-black/10 md:grid-cols-4">{steps.map((step) => { const Icon = step.icon; return <div key={step.n} className="lift group bg-[#fbfaf8] p-5 sm:p-6"><div className="flex items-center justify-between"><span className="eyebrow text-muted-foreground">{step.n}</span><Icon size={17} className="text-primary transition-transform group-hover:rotate-12" /></div><h3 className="display mt-10 text-xl font-semibold">{step.title}</h3><p className="mt-2 text-sm text-muted-foreground">{step.body}</p></div>; })}</div></div></section>

    <section className="border-b border-black/[.07] bg-[#21191a] py-16 text-white sm:py-20"><div className="container"><div className="grid items-center gap-10 lg:grid-cols-[.75fr_1.25fr] lg:gap-20"><div><div className="eyebrow text-[#ffb6ca]">A preview of what’s next</div><h2 className="display mt-4 text-4xl font-semibold leading-[.98] sm:text-5xl">Meet your AI Co-Designer.</h2><p className="mt-5 max-w-[410px] leading-7 text-white/60">Generate a direction, remix the edges, and refine the details without losing your point of view.</p><Link href="/features" className="mt-7 inline-flex items-center text-sm font-semibold text-[#ffb6ca]">See all Studio capabilities <ArrowRight className="ml-2" size={15} /></Link></div><div className="grid gap-3 sm:grid-cols-3"><div className="rounded-[1.25rem] border border-white/10 bg-white/[.06] p-5"><Command size={18} className="text-[#ffb6ca]" /><div className="mt-12 text-lg font-semibold">Generate</div><p className="mt-2 text-sm leading-6 text-white/50">Start with a direction.</p></div><div className="rounded-[1.25rem] border border-white/10 bg-white/[.06] p-5"><MousePointer2 size={18} className="text-[#ffb6ca]" /><div className="mt-12 text-lg font-semibold">Remix</div><p className="mt-2 text-sm leading-6 text-white/50">Explore what it could be.</p></div><div className="rounded-[1.25rem] border border-white/10 bg-white/[.06] p-5"><Check size={18} className="text-[#ffb6ca]" /><div className="mt-12 text-lg font-semibold">Refine</div><p className="mt-2 text-sm leading-6 text-white/50">Make it unmistakably yours.</p></div></div></div></div></section>

    <section className="container py-16 sm:py-20"><div className="flex items-end justify-between gap-6 border-b border-black/10 pb-6"><div><div className="eyebrow text-primary">A little fuel for the blank page</div><h2 className="display mt-3 text-3xl font-semibold sm:text-4xl">Find a direction. Then remix it.</h2></div><Link href="/inspiration" className="hidden text-sm font-semibold text-primary sm:inline-flex sm:items-center">View gallery <ArrowRight className="ml-2" size={15} /></Link></div><div className="mt-7 grid gap-4 md:grid-cols-3"><div className="group aspect-[1.15/1] overflow-hidden rounded-[1.25rem] bg-[#f4ece6] p-6"><div className="flex h-full flex-col justify-between"><div className="eyebrow text-black/45">PORTFOLIO / 01</div><div className="display text-4xl leading-[.82] transition-transform duration-300 group-hover:translate-x-2">Soft<br />structures<br /><span className="text-primary">/</span></div><div className="text-xs text-black/50">A study in quiet confidence.</div></div></div><div className="group aspect-[1.15/1] overflow-hidden rounded-[1.25rem] bg-[#e63b72] p-6 text-white"><div className="flex h-full flex-col justify-between"><div className="eyebrow text-white/60">EDITORIAL / 02</div><div className="display text-4xl leading-[.82] transition-transform duration-300 group-hover:translate-x-2">Pink<br /><span className="italic">noise.</span></div><div className="text-xs text-white/70">A magazine for a moving internet.</div></div></div><div className="group aspect-[1.15/1] overflow-hidden rounded-[1.25rem] bg-[#d8d5d0]"><img src="/manus-storage/luma-inspiration-01_48e35c2b.png" alt="Architecture-inspired website composition" className="h-full w-full object-cover transition-transform duration-500 group-hover:scale-105" /></div></div><Link href="/inspiration" className="mt-5 inline-flex items-center text-sm font-semibold text-primary sm:hidden">View full inspiration gallery <ArrowRight className="ml-2" size={15} /></Link></section>

    <MiniCTA />
  </div>;
}
