import { ArrowUpRight, Layers3, Sparkles, SlidersHorizontal } from "lucide-react";

export default function StudioPreview({ compact = false }: { compact?: boolean }) {
  return <div className={`soft-shadow relative overflow-hidden rounded-[1.35rem] border border-black/10 bg-[#eeebe9] ${compact ? "min-h-[380px]" : "min-h-[500px]"}`}>
    <div className="flex h-12 items-center justify-between border-b border-black/10 bg-white/75 px-4 backdrop-blur-sm"><div className="flex items-center gap-2"><span className="h-2.5 w-2.5 rounded-full bg-[#ff756f]" /><span className="h-2.5 w-2.5 rounded-full bg-[#f8c854]" /><span className="h-2.5 w-2.5 rounded-full bg-[#65ca8d]" /><span className="ml-3 font-mono text-[10px] text-black/45">luma / untitled-site</span></div><div className="pill px-2.5 py-1 font-mono text-[9px] text-black/55">desktop · 1440</div></div>
    <div className="flex min-h-[calc(100%-48px)]">
      <aside className="hidden w-[154px] shrink-0 border-r border-black/10 bg-white/55 p-3 sm:block"><div className="mb-4 flex items-center justify-between"><span className="font-mono text-[9px] uppercase tracking-wider text-black/45">Layers</span><Layers3 size={13} className="text-black/40" /></div><div className="space-y-1 font-mono text-[10px]"><div className="rounded-md bg-[#ffd8e3] px-2 py-2 text-[#8f1e48]">⌁ hero</div><div className="px-2 py-2 text-black/50">↳ navigation</div><div className="px-2 py-2 text-black/50">↳ heading</div><div className="px-2 py-2 text-black/50">↳ cta-button</div><div className="mt-3 border-t border-black/10 pt-3 px-2 text-black/50">⌁ features</div><div className="px-2 py-2 text-black/50">⌁ footer</div></div></aside>
      <div className="relative flex min-w-0 flex-1 items-center justify-center overflow-hidden bg-[#d8d0cc] p-5 sm:p-10"><div className="absolute inset-0 opacity-40" style={{backgroundImage: "linear-gradient(rgba(25,24,23,.08) 1px, transparent 1px),linear-gradient(90deg,rgba(25,24,23,.08) 1px,transparent 1px)", backgroundSize: "28px 28px"}} /><div className="relative z-10 aspect-[1.08/1] w-full max-w-[500px] overflow-hidden rounded-sm bg-[#fbfaf8] shadow-2xl"><div className="flex items-center justify-between border-b border-black/10 px-4 py-3"><div className="font-mono text-[9px] font-medium tracking-tight">ARCHIVE / 01</div><div className="flex gap-4 font-mono text-[8px] text-black/55"><span>INDEX</span><span>ABOUT</span><span>CONTACT</span></div></div><div className="relative h-[calc(100%-43px)] overflow-hidden p-5 sm:p-8"><div className="eyebrow text-black/45">A new kind of material</div><div className="display mt-4 max-w-[280px] text-[clamp(28px,4vw,52px)] font-semibold leading-[.9]">Make room for the unexpected.</div><div className="mt-6 flex items-center gap-2 font-mono text-[9px] text-black/50"><span className="h-1.5 w-1.5 rounded-full bg-[#e63b72]" /> Built in Luma Studio</div><div className="absolute -bottom-10 -right-14 h-52 w-52 rounded-full bg-[#f48da9] blur-[1px]" /><div className="absolute bottom-7 right-8 h-28 w-28 rotate-12 rounded-[40%] bg-[#ffd7dd] shadow-inner" /><div className="absolute bottom-6 left-5 h-[1px] w-[46%] bg-black/25" /></div></div><div className="absolute bottom-4 left-4 flex items-center gap-2 rounded-full border border-white/40 bg-white/70 px-3 py-2 text-[10px] font-semibold text-black/65 backdrop-blur"><Sparkles size={12} className="text-primary" /> AI Co-Designer is ready</div></div>
      <aside className="hidden w-[155px] shrink-0 border-l border-black/10 bg-white/55 p-3 md:block"><div className="mb-4 flex items-center justify-between"><span className="font-mono text-[9px] uppercase tracking-wider text-black/45">Properties</span><SlidersHorizontal size={13} className="text-black/40" /></div><div className="space-y-4 font-mono text-[9px] text-black/50"><div><div className="mb-2 flex justify-between"><span>width</span><span>100%</span></div><div className="h-1 rounded bg-black/10"><div className="h-1 w-4/5 rounded bg-primary" /></div></div><div><div className="mb-2 flex justify-between"><span>radius</span><span>12px</span></div><div className="h-1 rounded bg-black/10"><div className="h-1 w-2/5 rounded bg-primary" /></div></div><div className="border-t border-black/10 pt-3"><div className="mb-2">responsive</div><div className="flex gap-1"><div className="rounded bg-[#ffd8e3] px-2 py-1 text-[#8f1e48]">desk</div><div className="rounded bg-black/5 px-2 py-1">tab</div><div className="rounded bg-black/5 px-2 py-1">mob</div></div></div><div className="border-t border-black/10 pt-3"><div className="mb-2">fill</div><div className="flex items-center gap-2"><span className="h-4 w-4 rounded bg-[#fbfaf8] ring-1 ring-black/10" />#fbfaf8</div></div></div></aside>
    </div>
    {!compact && <div className="absolute bottom-4 right-4 hidden items-center gap-2 rounded-full bg-[#21191a] px-3 py-2 font-mono text-[9px] text-white/80 sm:flex"><ArrowUpRight size={12} className="text-[#ffb6ca]" /> remix this layout</div>}
  </div>;
}
