import { useState } from "react";
import { AlignLeft, ChevronDown, CircleDot, Layers3, LayoutTemplate, MousePointer2, PanelRight, Plus, Sparkles, Square, SlidersHorizontal, Type, WandSparkles } from "lucide-react";

export default function StudioPreview({ compact = false }: { compact?: boolean }) {
  const [tilt, setTilt] = useState({ x: 0, y: 0 });
  const onMove = (event: React.MouseEvent<HTMLDivElement>) => {
    const rect = event.currentTarget.getBoundingClientRect();
    const x = ((event.clientX - rect.left) / rect.width - 0.5) * 2;
    const y = ((event.clientY - rect.top) / rect.height - 0.5) * 2;
    setTilt({ x: y * -1.5, y: x * 1.5 });
  };

  return <div className={`studio-shell soft-shadow relative overflow-hidden rounded-[1.35rem] border border-black/10 bg-[#e9e4e1] ${compact ? "min-h-[380px]" : "min-h-[540px]"}`} onMouseMove={onMove} onMouseLeave={() => setTilt({ x: 0, y: 0 })}>
    <div className="studio-chrome flex h-12 items-center justify-between border-b border-black/10 bg-white/80 px-4 backdrop-blur-sm"><div className="flex items-center gap-2"><span className="h-2.5 w-2.5 rounded-full bg-[#ff756f]" /><span className="h-2.5 w-2.5 rounded-full bg-[#f8c854]" /><span className="h-2.5 w-2.5 rounded-full bg-[#65ca8d]" /><span className="ml-3 font-mono text-[10px] text-black/45">luma / untitled-site</span></div><div className="flex items-center gap-3"><span className="hidden font-mono text-[9px] text-black/40 sm:block">autosaved just now</span><div className="pill px-2.5 py-1 font-mono text-[9px] text-black/55">preview ↗</div></div></div>
    <div className="flex min-h-[calc(100%-48px)]">
      <aside className="hidden w-[174px] shrink-0 border-r border-black/10 bg-white/60 p-3 sm:block"><div className="mb-3 flex items-center justify-between"><span className="font-mono text-[9px] uppercase tracking-wider text-black/45">Structure</span><Plus size={13} className="text-black/40" /></div><div className="space-y-0.5 font-mono text-[10px]"><div className="rounded-md bg-[#ffd8e3] px-2 py-2 text-[#8f1e48]"><Layers3 size={11} className="mr-1.5 inline" />hero</div><div className="border-l border-black/10 pl-3"><div className="px-2 py-1.5 text-black/50">↳ navigation</div><div className="px-2 py-1.5 text-black/50">↳ eyebrow</div><div className="rounded bg-black/[.04] px-2 py-1.5 text-black/65">↳ heading</div><div className="px-2 py-1.5 text-black/50">↳ cta-group</div></div><div className="mt-1 rounded-md px-2 py-2 text-black/55"><LayoutTemplate size={11} className="mr-1.5 inline" />features</div><div className="rounded-md px-2 py-2 text-black/55"><Square size={11} className="mr-1.5 inline" />testimonial</div><div className="rounded-md px-2 py-2 text-black/55"><AlignLeft size={11} className="mr-1.5 inline" />footer</div></div><div className="mt-8 border-t border-black/10 pt-3"><div className="mb-2 font-mono text-[9px] uppercase tracking-wider text-black/40">Components</div><div className="grid grid-cols-3 gap-1"><div className="flex h-7 items-center justify-center rounded bg-black/[.04] text-black/45"><Type size={12} /></div><div className="flex h-7 items-center justify-center rounded bg-black/[.04] text-black/45"><Square size={12} /></div><div className="flex h-7 items-center justify-center rounded bg-black/[.04] text-black/45"><CircleDot size={12} /></div></div></div></aside>
      <div className="relative flex min-w-0 flex-1 items-center justify-center overflow-hidden bg-[#d5ceca] p-4 sm:p-8"><div className="absolute inset-0 opacity-35" style={{backgroundImage: "linear-gradient(rgba(25,24,23,.08) 1px, transparent 1px),linear-gradient(90deg,rgba(25,24,23,.08) 1px,transparent 1px)", backgroundSize: "28px 28px"}} /><div className="studio-canvas relative z-10 w-full max-w-[520px] transition-transform duration-300" style={{ transform: `perspective(1200px) rotateX(${tilt.x}deg) rotateY(${tilt.y}deg)` }}><div className="mb-2 flex items-center justify-between px-1 font-mono text-[9px] text-black/45"><span>canvas / home</span><span>1440 × 980</span></div><div className="relative aspect-[1.12/1] overflow-hidden rounded-sm bg-[#fbfaf8] shadow-2xl"><div className="flex items-center justify-between border-b border-black/10 px-4 py-3"><div className="font-mono text-[9px] font-medium tracking-tight">ARCHIVE / 01</div><div className="flex gap-4 font-mono text-[8px] text-black/55"><span>INDEX</span><span>ABOUT</span><span>CONTACT</span></div></div><div className="relative h-[calc(100%-43px)] overflow-hidden p-5 sm:p-8"><div className="eyebrow text-black/45">A new kind of material</div><div className="display mt-4 max-w-[290px] text-[clamp(28px,4vw,52px)] font-semibold leading-[.9]">Make room for the unexpected.</div><div className="mt-6 flex items-center gap-2 font-mono text-[9px] text-black/50"><span className="h-1.5 w-1.5 rounded-full bg-[#e63b72]" /> Built in Luma Studio</div><div className="absolute -bottom-10 -right-14 h-52 w-52 rounded-full bg-[#f48da9] blur-[1px]" /><div className="absolute bottom-7 right-8 h-28 w-28 rotate-12 rounded-[40%] bg-[#ffd7dd] shadow-inner" /><div className="absolute bottom-6 left-5 h-[1px] w-[46%] bg-black/25" /><div className="absolute left-5 top-[42%] h-[1px] w-28 bg-black/15" /></div></div><div className="mt-2 flex items-center justify-center gap-2 font-mono text-[9px] text-black/40"><span className="rounded bg-white/65 px-2 py-1">desktop</span><span className="rounded bg-black/[.06] px-2 py-1">tablet</span><span className="rounded bg-black/[.06] px-2 py-1">mobile</span></div></div><div className="absolute bottom-4 left-4 flex items-center gap-2 rounded-full border border-white/40 bg-white/75 px-3 py-2 text-[10px] font-semibold text-black/65 shadow-lg backdrop-blur"><Sparkles size={12} className="text-primary" /> AI Co-Designer is ready</div></div>
      <aside className="hidden w-[182px] shrink-0 border-l border-black/10 bg-white/60 p-3 md:block"><div className="mb-3 flex items-center justify-between"><span className="font-mono text-[9px] uppercase tracking-wider text-black/45">Inspector</span><PanelRight size={13} className="text-black/40" /></div><div className="space-y-4 font-mono text-[9px] text-black/50"><div><div className="mb-2 flex items-center justify-between"><span>typography</span><ChevronDown size={11} /></div><div className="rounded-md bg-black/[.04] p-2"><div className="font-sans text-[13px] font-semibold text-black/70">Syne / 64 px</div><div className="mt-1 text-[8px] text-black/40">weight 600 · line 0.9</div></div></div><div><div className="mb-2 flex items-center justify-between"><span>layout</span><SlidersHorizontal size={11} /></div><div className="grid grid-cols-2 gap-1"><div className="rounded bg-black/[.04] p-2">w / 100%</div><div className="rounded bg-black/[.04] p-2">gap / 24</div><div className="rounded bg-black/[.04] p-2">pad / 64</div><div className="rounded bg-black/[.04] p-2">r / 12</div></div></div><div><div className="mb-2 flex items-center justify-between"><span>fill</span><ChevronDown size={11} /></div><div className="flex items-center gap-2 rounded-md bg-black/[.04] p-2"><span className="h-4 w-4 rounded bg-[#fbfaf8] ring-1 ring-black/10" />#fbfaf8</div></div><div className="border-t border-black/10 pt-3"><div className="mb-2">ai suggestion</div><div className="rounded-md bg-[#ffd8e3] p-2 text-[8px] leading-4 text-[#8f1e48]">Try a softer contrast for the supporting line.</div></div></div></aside>
    </div>
    {!compact && <div className="absolute bottom-4 right-4 hidden items-center gap-2 rounded-full bg-[#21191a] px-3 py-2 font-mono text-[9px] text-white/80 shadow-lg sm:flex"><WandSparkles size={12} className="text-[#ffb6ca]" /> remix this layout</div>}
  </div>;
}
